###########################
# Configuration for rubocop
#
# Most of these are disabling existing cops, primarily
# due to a smattering of different styles and loose
# guidlines for contributions.
#
# Any of these may be changed.

MethodLength:
  Max: 200

LineLength:
  Max: 160

HashSyntax:
  Enabled: false

# Prefer single-quotes
StringLiterals:
  Enabled: true

AlignParameters:
  Enabled: false

SpaceAroundOperators:
  Enabled: false

Encoding:
  Enabled: false

AndOr:
  Enabled: true

EmptyLineBetweenDefs:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

RescueException:
  Enabled: false

Syntax:
  Enabled: false

WordArray:
  Enabled: false

IfUnlessModifier:
  Enabled: false

ParenthesesAroundCondition:
  Enabled: false

WhileUntilModifier:
  Enabled: false

Semicolon:
  Enabled: false

UnlessElse:
  Enabled: false

BlockNesting:
  Enabled: false

Proc:
  Enabled: false

Lambda:
  Enabled: false

CollectionMethods:
  Enabled: false

CaseIndentation:
  Enabled: false

FinalNewline:
  Enabled: true

AssignmentInCondition:
  Enabled: true

AllCops:
  Excludes:
    - vendor/**
